version: 2
updates:
  - package-ecosystem: composer
    directory: "/"
    schedule:
      interval: monthly
    cooldown:
      default-days: 7
    open-pull-requests-limit: 5
    labels:
      - dependencies
      - php
    commit-message:
      prefix: chore
      prefix-development: chore
      include: scope
    groups:
      production-dependencies:
        dependency-type: production
      dev-dependencies:
        dependency-type: development
      production-security:
        applies-to: security-updates
        dependency-type: production
      dev-security:
        applies-to: security-updates
        dependency-type: development

  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: monthly
    cooldown:
      default-days: 7
    open-pull-requests-limit: 5
    labels:
      - dependencies
      - github_actions
    commit-message:
      prefix: chore
      include: scope
    groups:
      github-actions:
        patterns:
          - "*"
